name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/info-circle-svgrepo-com.svg
    - assets/close-delete-remove-cancel-cross-svgrepo-com.svg
    - assets/graph.png
    - assets/profile-round-1342-svgrepo-com.svg

